#!/bin/sh

# if [[ -r /dev/video0 || -r /dev/video1 ]]
# then zsh <<< "kitty sh -c 'echo \"Disabling camera ...\"
# sudo chmod -r /dev/video*' &"; fi &


destroy() { pkill -f "DISPLAY=$DISPLAY $*"; }
spawn() #[
{
        ## v3.0
        setsid sh -c "$(echo                    \
        'trap' "'kill 0'" 'HUP INT TERM;'       \
        "DISPLAY=$DISPLAY $* &> /dev/null &"    \
        'wait $!'                               \
        )"

        ## v2.0
        # setsid sh -c "trap 'kill 0' HUP INT TERM; \
        # DISPLAY=$DISPLAY $* &> /dev/null & \
        # wait \$!"

        ## v1.0
        # sh -c "trap 'kill \$(jobs -p)' HUP INT TERM; \
        # DISPLAY=$DISPLAY $* &> /dev/null & \
        # wait \$!" &
} #]

xsetroot -cursor_name left_ptr &
xset r rate 300 20

bspc config border_width        10
bspc config window_gap          20
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config single_monocle      true
bspc config initial_polarity    first_child
bspc config status_prefix       W:

bspc config normal_border_color  '#808080'
bspc config active_border_color  '#404040'
bspc config focused_border_color '#000000'

bspc config focus_follows_pointer       true
bspc config pointer_follows_focus       true
bspc config pointer_follows_monitor     true
bspc config merge_overlapping_monitors  true
bspc config ignore_ewmh_struts          true

# NOTE: use `xprop | grep ^WM_NAME` to get these values
bspc rule -a VirtualBoxVM state=floating border=off
bspc rule -a "VirtualBox Machine" state=tiled border=off
bspc rule -a jome state=floating border=off
bspc rule -a '*:*:Picture-in-Picture' state=floating layer=above sticky=on focus=off border=off
bspc rule -a '*:*:Picture-in-picture' state=floating layer=above sticky=on focus=off border=off
bspc rule -a Safeeyes state=floating layer=above fullscreen=off focus=off
bspc rule -a Clipster layer=above
bspc rule -a mpv state=pseudo_tiled border=off
bspc rule -a GParted state=floating layer=above
bspc rule -a feh state=floating layer=above focus=on border=off
bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled

destroy sxhkd
spawn sxhkd $(test $(uname) = Linux && echo ~/.config/sxhkd/linux)

pgrep -f "DISPLAY=$DISPLAY urxvtd -q -o" \
|| spawn urxvtd -q -o

destroy xmousepasteblock
spawn xmousepasteblock

# destroy xcompmgr
# spawn xcompmgr

destroy picom
spawn picom
# spawn picom --experimental-backends

# destroy clipster
# spawn clipster -d

# destroy safeeyes
# spawn safeeyes -e

xmodmap -e 'add Lock = XF86Favorites' && \
xmodmap -e 'remove Lock = Caps_Lock' && \
xmodmap -e 'remove control = Control_L' && \
xmodmap -e 'keysym Caps_Lock = Control_L' && \
xmodmap -e 'add control = Control_L' && \
spawn xcape -d -t 300 -e Control_L=XF86Favorites


test -x ~/.config/bspwm/desktop_manager ||  \
cc ~/.config/bspwm/desktop_manager.c        \
-o ~/.config/bspwm/desktop_manager          \
-O9 -fpie -static

destroy bspc subscribe report
spawn 'bspc subscribe report | ~/.config/bspwm/desktop_manager | /bin/sh'

# vim:set et ts=4 sw=8 sts=0 fdm=marker fmr=[,]:
