#!/bin/bash
# Default acpi script that takes an entry for all actions

case "$1" in
    button/power) #[
        case "$2" in
            PBTN|PWRF)
                logger 'PowerButton pressed'
                ;;
            *)  logger "ACPI action undefined: $1 / $2"
        esac
        ;; #]
    button/sleep) #[
        case "$2" in
            SLPB|SBTN)
                logger 'SleepButton pressed'
                zzz
                ;;
            *)  logger "ACPI action undefined: $1 / $2"
        esac
        ;; #]
    button/lid) #[
        case "$3" in
            close)
                logger 'LID closed'
                if !  test -f "$(dirname "$0")/lid_sleep"
                then
                    touch "$(dirname "$0")/lid_sleep"
                    echo 0 > "$(dirname "$0")/lid_sleep"
                    chmod 0666 "$(dirname "$0")/lid_sleep"
                fi
                if test 1 = "$(cut -c 1 "$(dirname "$0")/lid_sleep")"
                then 
                    logger Sleeping...
                    zzz
                fi
                ;;
            open)
                logger 'LID opened'
                ;;
            *)  logger "ACPI action undefined: $1 / $2"
        esac
        ;; #]
    ac_adapter) #[
        case "$2" in
            AC|ACAD|ADP0)
                case "$4" in
                    00000000)
                        logger 'AC unpluged'
                        ;;
                    00000001)
                        logger 'AC pluged'
                        ;;
                esac
                ;;
            *)  logger "ACPI action undefined: $1 / $2"
        esac
        ;; #]
    battery) #[
        case "$2" in
            BAT0)
                case "$4" in
                    00000000)
                        logger 'Battery online'
                        ;;
                    00000001)
                        logger 'Battery offline'
                        ;;
                esac
                ;;
            CPU0)
                ;;
            *)  logger "ACPI action undefined: $1 / $2"
        esac
        ;; #]
    video/brightness*) #[
        case "$2" in
            BRTUP)
                logger Brightness up button pressed
                /usr/local/bin/light +2
                ;;
            BRTDN)
                logger Brightness down button pressed
                /usr/local/bin/light -2
                ;;
            *)  logger "ACPI action undefined: $1 / $2"
        esac
        ;; #]
    button/volume*) #[
        case "$2" in
            VOLUP)
                logger Volume up button pressed
                amixer set Master -Mq 5%+
                ;;
            VOLDN)
                logger Volume down button pressed
                amixer set Master -Mq 5%-
                ;;
            *)  logger "ACPI action undefined: $1 / $2"
        esac
        ;; #]
    button/mute) #[
        case "$2" in
            MUTE)
                logger Mute button pressed. Toggling mute.
                amixer set Master -q toggle
                ;;
            *)  logger "ACPI action undefined: $1 / $2"
        esac
        ;; #]
    button/f20) #[
        case "$2" in
            F20)
                logger F20 button pressed, assuming as MicMute.
                amixer set Capture -q toggle
                ;;
            *)  logger "ACPI action undefined: $1 / $2"
        esac
        ;; #]
    *) #[
        logger "ACPI group/action undefined: $1 / $2"
        ;; #]
esac

# vim:set ts=2 sw=4 ft=sh et fdm=marker fmr=[,]:
